name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.15
  - pandas=2.1.3
  - pyarrow
  - pytest
  - scipy
  - pip
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
