name: nyc_airbnb_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.15
  - pyarrow
  - pip
  - pip:
      - mlflow==2.4.2
      - databricks-cli
      - hydra-core>=1.1
      - pandas
      - requests
      - scipy
      - scikit-learn
      - wandb