name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.15  # Specify exact version
  - pip
  - requests=2.24.0
  - pyarrow
  - pip:
      - mlflow==2.8.1
      - wandb
      - wandb-utils
